stages:
  - build
  - deploy
  - publish

.job_build_template:
  stage: build
  image: docker:19.03
  before_script:
    - apk add --update py-pip
    - pip install awscli --upgrade
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - >-
      docker build --build-arg APP_ENV=$ENV -t $ECR_URL/$PROJECT/$ENV/$REPOSITORY:latest 
      -t $ECR_URL/$PROJECT/$ENV/$REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - >-
      aws ecr get-login-password --region $AWS_DEFAULT_REGION | 
      docker login --username AWS --password-stdin $ECR_URL
    - docker push $ECR_URL/$PROJECT/$ENV/$REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $ECR_URL/$PROJECT/$ENV/$REPOSITORY:latest
    - docker logout $ECR_URL

.job_deploy_template:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  before_script:
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script:
    - >-
      aws ecs update-service --region $AWS_DEFAULT_REGION --service $SERVICE_NAME 
      --cluster $PROJECT-$ENV --force-new-deployment
    - aws ecs wait services-stable --services $SERVICE_NAME --cluster $PROJECT-$ENV

.job_publish_template:
  stage: publish
  image: docker:19.03
  before_script:
    - apk add --update py-pip
    - pip install awscli --upgrade
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - >-
      docker build --build-arg APP_ENV=$ENV -t $ECR_URL/$REPOSITORY:latest 
      -t $ECR_URL/$REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - >-
      aws ecr get-login-password --region $AWS_DEFAULT_REGION | 
      docker login --username AWS --password-stdin $ECR_URL
    - docker push $ECR_URL/$REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $ECR_URL/$REPOSITORY:latest
    - docker logout $ECR_URL/$REPOSITORY

dev_build:
  extends: .job_build_template
  stage: build
  environment:
    name: dev
  only:
    - main
  tags:
    - local

dev_deploy:
  extends: .job_deploy_template
  stage: deploy
  environment:
    name: dev
  only:
    - main
  tags:
    - local

dev_publish:
  extends: .job_publish_template
  environment:
    name: publish
  variables:
    ENV: "dev"
  only:
    - /^v.*$/
  tags:
    - local
