version: "1"

services:
  ssr:
    image: dksh_ssr_img_${ENV:-dev}
    # container_name: dksh_ssr_container
    build:
      context: .
      dockerfile: Dockerfile.ssr.${ENV:-dev}
    ports:
      - 4000:4000
