version: "1"

services:
  ssr:
    image: dksh_img
    container_name: dksh_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    # enviroment:
    #   - ABC:123
    # volumes:
    #   - .:/usr/src/app
    # depends_on:
    #   - db
    # v14.15
