import { NewVideoItemInfoNewArticleModel } from "src/app/common-tool/new-video/new-video.model";

export const WillingnessLearnItem: NewVideoItemInfoNewArticleModel[] = [
  {
    id: '1',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師．3,567 已觀看',
  },
  {
    id: '2',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師．2,967 已觀看',
  },
  {
    id: '3',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '間歇性斷食操作指南',
    text: '王音名 醫師．1,567 已觀看',
  },
  {
    id: '4',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '二手菸對人體的危害',
    text: '邵昕 醫師．2,567 已觀看',
  },
  {
    id: '5',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師．3,567 已觀看',
  },
  {
    id: '6',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師．2,967 已觀看',
  },
  {
    id: '7',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/new_video_fake_img.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '從小實施衛教的重要性',
    text: '歐朔銘 醫師．4,567 已觀看',
  },
  {
    id: '8',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '為什麼流感會致命？',
    text: '林美麗 醫師．3,567 已觀看',
  },
  {
    id: '9',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '教你如何分辨醫療口罩',
    text: '王彩華 醫師．2,567 已觀看',
  },
  {
    id: '10',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '防曬，從小做起',
    text: '歐朔銘 醫師．2,567 已觀看',
  },
  {
    id: '11',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師．3,567 已觀看',
  },
  {
    id: '12',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師．2,967 已觀看',
  },
  {
    id: '13',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '間歇性斷食操作指南',
    text: '王音名 醫師．1,567 已觀看',
  },
  {
    id: '14',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '二手菸對人體的危害',
    text: '邵昕 醫師．2,567 已觀看',
  },
  {
    id: '15',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師．3,567 已觀看',
  },
  {
    id: '16',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師．2,967 已觀看',
  },
  {
    id: '17',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/new_video_fake_img.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '從小實施衛教的重要性',
    text: '歐朔銘 醫師．4,567 已觀看',
  },
  {
    id: '18',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '為什麼流感會致命？',
    text: '林美麗 醫師．3,567 已觀看',
  },
  {
    id: '19',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '教你如何分辨醫療口罩',
    text: '王彩華 醫師．2,567 已觀看',
  },
  {
    id: '20',
    type: '醫務管理',
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '防曬，從小做起',
    text: '歐朔銘 醫師．2,567 已觀看',
  },
];
