import { NewActiveItemInfoNewArticleModel } from '../new-active/new-active.model';
import { NewArticleModel } from '../new-article/new-article.modal';

export const NewArticle: NewArticleModel[] = [
  {
    id: '1',
    articleImg: '../../../assets/img/fakeImge/new_article_1.png',
    articleTitle: '加護病房靜脈同時給予多種藥品之型態與風險',
    articleSubtitle: '對某醫學中心11個加護病房的護理師問券調查，以了解同時竟賣給多種藥的型態與風險。',
    author: '黃織芬',
    authorImg: '../../../assets/img/fakeImge/new_article_headshot_1.png',
    viewer: '2021/05/11．1,567',
  },
  {
    id: '2',
    articleImg: '../../../assets/img/fakeImge/new_article_2.png',
    articleTitle: '甲狀腺癌術後病人採低碘飲食持續時間對尿碘濃度之影響',
    articleSubtitle: '本研究目的為探討甲狀腺癌術後病人採低碘飲食的持續時間對尿碘濃度之影響。',
    author: '黃織芬',
    authorImg: '../../../assets/img/fakeImge/header_fake_headshot.png',
    viewer: '2021/05/11．1,567',
  },
  {
    id: '3',
    articleImg: '../../../assets/img/fakeImge/new_article_1.png',
    articleTitle: '加護病房靜脈同時給予多種藥品之型態與風險',
    articleSubtitle: '對某醫學中心11個加護病房的護理師問券調查，以了解同時竟賣給多種藥的型態與風險。',
    author: '黃織芬',
    authorImg: '../../../assets/img/fakeImge/new_article_headshot_1.png',
    viewer: '2021/05/11．1,567',
  },
  {
    id: '4',
    articleImg: '../../../assets/img/fakeImge/new_article_2.png',
    articleTitle: '甲狀腺癌術後病人採低碘飲食持續時間對尿碘濃度之影響',
    articleSubtitle: '本研究目的為探討甲狀腺癌術後病人採低碘飲食的持續時間對尿碘濃度之影響。',
    author: '黃織芬',
    authorImg: '../../../assets/img/fakeImge/header_fake_headshot.png',
    viewer: '2021/05/11．1,567',
  },
  {
    id: '5',
    articleImg: '../../../assets/img/fakeImge/new_article_1.png',
    articleTitle: '加護病房靜脈同時給予多種藥品之型態與風險',
    articleSubtitle: '對某醫學中心11個加護病房的護理師問券調查，以了解同時竟賣給多種藥的型態與風險。',
    author: '黃織芬',
    authorImg: '../../../assets/img/fakeImge/new_article_headshot_1.png',
    viewer: '2021/05/11．1,567',
  },
];

export const NewActiveItemInfo: NewActiveItemInfoNewArticleModel[] = [
  {
    id: '1',
    img: '../../../assets/img/fakeImge/new_active_fake_img.png',
    tag: ['線上研討會', '系列講座'],
    title: '110年安泰醫療社團法人安泰醫院辦理醫護人員教育訓練計畫',
    subTitle: '地點：安泰醫院',
    headShot: '../../../assets/img/fakeImge/new_active_fake_headshot.png',
    name: '黃織芬 教授',
    time: '2021/05/11 19:00-2021/05/13 17:00',
  },
  {
    id: '2',
    img: '../../../assets/img/fakeImge/new_active_fake_img_2.png',
    tag: ['實體活動'],
    title: '臺中榮民總醫院感染科與小兒科聯合討論會',
    subTitle: '地點：臺中榮民總醫院',
    headShot: '../../../assets/img/fakeImge/new_active_fake_headshot.png',
    name: '黃織芬 教授',
    time: '2021/05/11 19:00-2021/05/13 17:00',
  },
  {
    id: '3',
    img: '../../../assets/img/fakeImge/new_active_fake_img.png',
    tag: ['線上研討會', '系列講座'],
    title: '110年安泰醫療社團法人安泰醫院辦理醫護人員教育訓練計畫',
    subTitle: '地點：安泰醫院',
    headShot: '../../../assets/img/fakeImge/new_active_fake_headshot.png',
    name: '黃織芬 教授',
    time: '2021/05/11 19:00-2021/05/13 17:00',
  },
  {
    id: '4',
    img: '../../../assets/img/fakeImge/new_active_fake_img_2.png',
    tag: ['實體活動'],
    title: '臺中榮民總醫院感染科與小兒科聯合討論會',
    subTitle: '地點：臺中榮民總醫院',
    headShot: '../../../assets/img/fakeImge/new_active_fake_headshot.png',
    name: '黃織芬 教授',
    time: '2021/05/11 19:00-2021/05/13 17:00',
  },
  {
    id: '5',
    img: '../../../assets/img/fakeImge/new_active_fake_img.png',
    tag: ['系列講座'],
    title: '110年安泰醫療社團法人安泰醫院辦理醫護人員教育訓練計畫',
    subTitle: '地點：安泰醫院',
    headShot: '../../../assets/img/fakeImge/new_active_fake_headshot.png',
    name: '黃織芬 教授',
    time: '2021/05/11 19:00-2021/05/13 17:00',
  },
  {
    id: '6',
    img: '../../../assets/img/fakeImge/new_active_fake_img_2.png',
    tag: ['實體活動'],
    title: '臺中榮民總醫院感染科與小兒科聯合討論會',
    subTitle: '地點：臺中榮民總醫院',
    headShot: '../../../assets/img/fakeImge/new_active_fake_headshot.png',
    name: '黃織芬 教授',
    time: '2021/05/11 19:00-2021/05/13 17:00',
  },
];
