import { NewVideoItemInfoNewArticleModel } from "src/app/common-tool/new-video/new-video.model";

export const FeatureVideoItem: NewVideoItemInfoNewArticleModel[] = [
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師•3,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師•2,967 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '間歇性斷食操作指南',
    text: '王音名 醫師•1,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '二手菸對人體的危害',
    text: '邵昕 醫師•2,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師•3,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師•2,967 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/new_video_fake_img.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '從小實施衛教的重要性',
    text: '歐朔銘 醫師•4,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '為什麼流感會致命？',
    text: '林美麗 醫師•3,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '教你如何分辨醫療口罩',
    text: '王彩華 醫師•2,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '防曬，從小做起',
    text: '歐朔銘 醫師•2,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師•3,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師•2,967 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '間歇性斷食操作指南',
    text: '王音名 醫師•1,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '二手菸對人體的危害',
    text: '邵昕 醫師•2,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_1.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '社區普篩可行性？',
    text: '歐朔銘 醫師•3,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/video_recommend_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_4.png',
    title: '寵物恐感新冠肺炎？',
    text: '林美麗 醫師•2,967 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/new_video_fake_img.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '從小實施衛教的重要性',
    text: '歐朔銘 醫師•4,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_2.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_2.png',
    title: '為什麼流感會致命？',
    text: '林美麗 醫師•3,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_3.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot.png',
    title: '教你如何分辨醫療口罩',
    text: '王彩華 醫師•2,567 已觀看',
  },
  {
    time: '32:24',
    headUrl: '../../../assets/img/fakeImge/newvideo_4.png',
    headShotUrl: '../../../assets/img/fakeImge/new_video_fake_headshot_3.png',
    title: '防曬，從小做起',
    text: '歐朔銘 醫師•2,567 已觀看',
  },
];
