import { HotSubjectItemInfoNewArticleModel } from "src/app/common-tool/hot-subject/hot-subject.model";

export const HotSubjectItemInfo: HotSubjectItemInfoNewArticleModel[] = [
  {
    id: '1',
    title: '眼科',
    subTitle: '121相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/eyes.png',
  },
  {
    id: '2',
    title: '小兒科',
    subTitle: '31相關課程',
    svgClass: 'babyIcon',
    url: '../../../assets/img/subject/baby.png',
  },
  {
    id: '3',
    title: '耳鼻喉科',
    subTitle: '93相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/ear.png',
  },
  {
    id: '4',
    title: '骨科',
    subTitle: '251相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/bone.png',
  },
  {
    id: '5',
    title: '腦科',
    subTitle: '121相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/brain.png',
  },
  {
    id: '6',
    title: '精神科',
    subTitle: '31相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/mind.png',
  },
  {
    id: '7',
    title: '皮膚科',
    subTitle: '93相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/skin.png',
  },
  {
    id: '8',
    title: '牙科',
    subTitle: '251相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/teeth.png',
  },
  {
    id: '9',
    title: '急診科',
    subTitle: '121相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/emergency.png',
  },
  {
    id: '10',
    title: '家醫科',
    subTitle: '31相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/home_medicine.png',
  },
  {
    id: '11',
    title: '內科',
    subTitle: '93相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/internal_medicine.png',
  },
  {
    id: '12',
    title: '婦產科',
    subTitle: '251相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/maternity.png',
  },
  {
    id: '13',
    title: '放射科',
    subTitle: '121相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/radiation.png',
  },
  {
    id: '14',
    title: '復健科',
    subTitle: '31相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/rehabilitation.png',
  },
  {
    id: '15',
    title: '重症醫學科',
    subTitle: '93相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/severe.png',
  },
  {
    id: '16',
    title: '外科',
    subTitle: '251相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/surgical.png',
  },
  {
    id: '17',
    title: '泌尿科',
    subTitle: '121相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/urology.png',
  },
  {
    id: '18',
    title: '麻醉科',
    subTitle: '251相關課程',
    svgClass: 'eyeIcon',
    url: '../../../assets/img/subject/anesthesiology.png',
  },
];
